# Copy this config into a yaml file 'app_config.yaml' in the same directory
# and enter your Twitter api key and secret here.
twitter:
  consumer_key: ""
  consumer_secret: ""

# Sentry (https://sentry.io) is used to report errors in release mode.
# If the DSN is left empty, errors that occur in release mode are not reported.
# For more information see https://pub.dev/packages/sentry
sentry:
  dsn: ""
