name: harpy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  oauth1: ^1.0.4
  logging: ^0.11.3+2
  logs:
    git: https://github.com/pq/logs
  intl: ^0.15.7
  cached_network_image: ^1.0.0
  photo_view: ^0.5.0
  provider: ^2.0.1+1
  flutter_material_color_picker: ^0.0.5
  flutter_hsvcolor_picker: ^0.0.1
  flare_flutter: ^1.5.1
  flushbar: 1.7.1+1
  mime_type: ^0.2.4
  get_it: ^1.0.3+2
  sembast: ^2.0.1
  shimmer: # todo: use pub version if pr gets merged and released
    git: git://github.com/robertodoering/flutter_shimmer.git
  sentry: ^2.2.0

  flutter_twitter_login:
    git: git://github.com/robertodoering/flutter_twitter_login.git
  url_launcher: ^5.0.1
  video_player: ^0.10.2+1
  webview_flutter: ^0.3.6
  path_provider: ^0.5.0+1
  connectivity: ^0.4.2
  shared_preferences: ^0.5.2+1
  file_picker: ^1.3.8
  device_info: ^0.4.0+3
  package_info: ^0.4.0+6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  mockito: ^4.0.0
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/flare/

  fonts:
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
